### ISSUE TITLE
Segfault when creating QGraphicsScene

### ISSUE THREAD

**Issue by phoe** [commonqt/commonqt#34]
Evaluating `(#_new QGraphicsScene)` results in a segfault on my machine.

`*inferior-lisp*` says:
```
CORRUPTION WARNING in SBCL pid 25607(tid 0x7ffff47ef700):
Memory fault at 0x8 (pc=0x7fffe6eaa295, sp=0x7ffff47edaa0)
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
```

Backtrace from SBCL 1.4.3:
```
Unhandled memory fault at #x8.
   [Condition of type SB-SYS:MEMORY-FAULT-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {100526FF93}>)

Backtrace:
  0: (SB-SYS:MEMORY-FAULT-ERROR #<unused argument> #.(SB-SYS:INT-SAP #X00000008))
      Locals:
        SB-KERNEL::ADDRESS-SAP = #.(SB-SYS:INT-SAP #X00000008)
  1: ("foreign function: call_into_lisp")
      [No Locals]
  2: ("foreign function: funcall2")
      [No Locals]
  3: ("foreign function: handle_trap")
      [No Locals]
  4: ("foreign function: #x4195A0")
      [No Locals]
  5: ((LABELS QT::ARGLIST-MARSHALLER :IN QT::ARGLIST-MARSHALLER) NIL #<CLOSURE (LAMBDA (QT::STACK) :IN QT::%%CALL) {1004D588FB}>)
      Locals:
        QT::ARGLIST = NIL
        QT::FINAL-CONT = #<CLOSURE (LAMBDA (QT::STACK) :IN QT::%%CALL) {1004D588FB}>
  6: (QT::%%NEW #<Qt::QGraphicsScene  {1004D58233}> NIL #<CLOSURE (LABELS QT::ARGLIST-MARSHALLER :IN QT::ARGLIST-MARSHALLER) {1004D5886B}> #.(SB-SYS:INT-SAP #X7FFFE2D7BF60) 123 #.(SB-SYS:INT-SAP #X7FFFEC03..
      Locals:
        QT::ARGLIST-MARSHALLER = #<CLOSURE (LABELS QT::ARGLIST-MARSHALLER :IN QT::ARGLIST-MARSHALLER) {1004D5886B}>
        QT::ARGS = NIL
        QT::BINDING = #.(SB-SYS:INT-SAP #X7FFFEC03B600)
        QT::CLASSFN = #.(SB-SYS:INT-SAP #X7FFFE2D7BF60)
        QT::INSTANCE = #<Qt::QGraphicsScene  {1004D58233}>
        QT::METHOD-INDEX = 123
  7: (SB-INT:SIMPLE-EVAL-IN-LEXENV ((LAMBDA NIL (OPTIMIZED-NEW "QGraphicsScene"))) #<NULL-LEXENV>)
  8: (EVAL ((LAMBDA NIL (OPTIMIZED-NEW "QGraphicsScene"))))
 --more--
```

My OS is `Linux localhost 4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Issue happens both on CommonQt available currently on Quicklisp and on CommonQt cloned from git master.

Issue happens both on SBCL 1.4.2 and 1.4.3.

This issue is weird, because @Shinmera was unable to reproduce it on their machine.

**Comment by stassats** [comment]
Yes, it's not reproducible.

**Comment by phoe** [comment]
GDB says:

```
Thread 1 "sbcl" received signal SIGSEGV, Segmentation fault.
0x0000000000437093 in alloc_immobile_obj (page_attributes=921600, 
    header=2319355470248152409) at immobile-space.c:382
382	              && __sync_bool_compare_and_swap((lispobj*)obj_ptr,
```

```
(gdb) thread apply all bt

Thread 1 (Thread 0x7ffff7fcc700 (LWP 5016)):
#0  0x0000000000437093 in alloc_immobile_obj (page_attributes=921600, 
    header=2319355470248152409) at immobile-space.c:382
#1  alloc_layout (slots=140737331523759) at immobile-space.c:1541
#2  0x0000000021d26f32 in ?? ()
#3  0x00000000000000d9 in ?? ()
#4  0x000000000000001a in ?? ()
#5  0x0000000000000004 in ?? ()
#6  0x0bfb7025185c9934 in ?? ()
#7  0x0000001000d3dcc3 in ?? ()
#8  0x0000000020100017 in ?? ()
#9  0x00000010000017bf in ?? ()
#10 0xfffffffffffffffe in ?? ()
#11 0x0000000000000002 in ?? ()
#12 0x0000000020100017 in ?? ()
#13 0xfffffffffffffffe in ?? ()
#14 0x00000010000017bf in ?? ()
#15 0x0000000020100017 in ?? ()
#16 0x0000000020100017 in ?? ()
#17 0x00000010000064bf in ?? ()
#18 0x0000000021d26d42 in ?? ()
#19 0xfffffffffffffffe in ?? ()
---Type <return> to continue, or q <return> to quit---
#20 0x00000000203ab84f in ?? ()
#21 0x0000000000000004 in ?? ()
#22 0x00000000203ab93f in ?? ()
#23 0x0000000020100017 in ?? ()
#24 0x00000000203a9d8f in ?? ()
#25 0x0000001000d3dcc3 in ?? ()
#26 0x00000000203ab8df in ?? ()
#27 0x0000000000000002 in ?? ()
#28 0x00000000203ab87f in ?? ()
#29 0x0000000020100017 in ?? ()
#30 0x00000010000017bf in ?? ()
#31 0x00000010000064bf in ?? ()
#32 0x0000000020100017 in ?? ()
#33 0x0000000020100017 in ?? ()
#34 0x00000010000017bf in ?? ()
#35 0xfffffffffffffffe in ?? ()
#36 0x0000000000000002 in ?? ()
#37 0xfffffffffffffffe in ?? ()
#38 0x00000010000017bf in ?? ()
#39 0x0000000020100017 in ?? ()
#40 0x0000000000000002 in ?? ()
#41 0x0000001000d3dcc3 in ?? ()
#42 0x0000000000000000 in ?? ()

```

**Comment by phoe** [comment]
A seemingly much more useful backtrace:

```
Thread 1 "sbcl" received signal SIGSEGV, Segmentation fault.
0x00007ffff4c15ae5 in QGraphicsScenePrivate::init() ()
   from /home/emiherd/.roswell/lisp/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/standalone/qtlibs!QtGui.so
(gdb) thread apply all bt

Thread 1 (Thread 0x7ffff7fcc700 (LWP 5016)):
#0  0x00007ffff4c15ae5 in QGraphicsScenePrivate::init() ()
   from /home/emiherd/.roswell/lisp/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/standalone/qtlibs!QtGui.so
#1  0x00007ffff4c15b94 in QGraphicsScene::QGraphicsScene(QObject*) ()
   from /home/emiherd/.roswell/lisp/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/standalone/qtlibs!QtGui.so
#2  0x00007ffff0e55ce0 in __smokeqtgui::x_QGraphicsScene::x_123(Smoke::StackItem*) ()
   from /home/emiherd/.roswell/lisp/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/standalone/qtlibs!smokeqtgui.so
#3  0x00007ffff0e4e0cd in __smokeqtgui::xcall_QGraphicsScene(short, void*, Smoke::StackItem*) ()
   from /home/emiherd/.roswell/lisp/quicklisp/dists/quicklisp/software/qt-libs-20171227-git/standalone/qtlibs!smokeqtgui.so
#4  0x000000002292302e in ?? ()
#5  0x00007ffff6a6f65f in ?? ()
#6  0x0000000020100017 in ?? ()
#7  0x00000000000000ad in ?? ()
#8  0x0000000000000004 in ?? ()
#9  0x00007ffff6a6f790 in ?? ()
---Type <return> to continue, or q <return> to quit---
#10 0x0000000022924bae in ?? ()
#11 0x0000000022922e83 in ?? ()
#12 0x00007ffff6a6f640 in ?? ()
#13 0x00007ffff6a6f678 in ?? ()
#14 0x0000001002297c43 in ?? ()
#15 0x0000001002298b8f in ?? ()
#16 0x00000000000000f6 in ?? ()
#17 0x0000001002298b2f in ?? ()
#18 0x0000000000000000 in ?? ()
(gdb) 
```

**Comment by phoe** [comment]
I'm an idiot - I forgot to create a QApplication first.
